// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.brett.schedulingapi;

import com.brett.schedulingapi.TimeSlot;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect TimeSlot_Roo_Configurable {
    
    declare @type: TimeSlot: @Configurable;
    
}
