// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.brett.schedulingapi;

import com.brett.schedulingapi.Vendor;

privileged aspect Vendor_Roo_JavaBean {
    
    public String Vendor.getName() {
        return this.name;
    }
    
    public void Vendor.setName(String name) {
        this.name = name;
    }
    
}
