// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.brett.schedulingapi;

import com.brett.schedulingapi.VendorIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect VendorIntegrationTest_Roo_Configurable {
    
    declare @type: VendorIntegrationTest: @Configurable;
    
}
