// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.brett.schedulingapi;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect VendorDataOnDemand_Roo_DataOnDemand {
    
    declare @type: VendorDataOnDemand: @Component;
    
    private Random VendorDataOnDemand.rnd = new SecureRandom();
    
    private List<Vendor> VendorDataOnDemand.data;
    
    public Vendor VendorDataOnDemand.getNewTransientVendor(int index) {
        Vendor obj = new Vendor();
        setName(obj, index);
        return obj;
    }
    
    public void VendorDataOnDemand.setName(Vendor obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public Vendor VendorDataOnDemand.getSpecificVendor(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Vendor obj = data.get(index);
        Long id = obj.getId();
        return Vendor.findVendor(id);
    }
    
    public Vendor VendorDataOnDemand.getRandomVendor() {
        init();
        Vendor obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Vendor.findVendor(id);
    }
    
    public boolean VendorDataOnDemand.modifyVendor(Vendor obj) {
        return false;
    }
    
    public void VendorDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Vendor.findVendorEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Vendor' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Vendor>();
        for (int i = 0; i < 10; i++) {
            Vendor obj = getNewTransientVendor(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
