// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.brett.schedulingapi;

import com.brett.schedulingapi.VendorDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect VendorDataOnDemand_Roo_Configurable {
    
    declare @type: VendorDataOnDemand: @Configurable;
    
}
