// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.brett.schedulingapi;

import com.brett.schedulingapi.Vendor;
import com.brett.schedulingapi.VendorDataOnDemand;
import com.brett.schedulingapi.VendorIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect VendorIntegrationTest_Roo_IntegrationTest {
    
    declare @type: VendorIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: VendorIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: VendorIntegrationTest: @Transactional;
    
    @Autowired
    VendorDataOnDemand VendorIntegrationTest.dod;
    
    @Test
    public void VendorIntegrationTest.testCountVendors() {
        Assert.assertNotNull("Data on demand for 'Vendor' failed to initialize correctly", dod.getRandomVendor());
        long count = Vendor.countVendors();
        Assert.assertTrue("Counter for 'Vendor' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void VendorIntegrationTest.testFindVendor() {
        Vendor obj = dod.getRandomVendor();
        Assert.assertNotNull("Data on demand for 'Vendor' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Vendor' failed to provide an identifier", id);
        obj = Vendor.findVendor(id);
        Assert.assertNotNull("Find method for 'Vendor' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Vendor' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void VendorIntegrationTest.testFindAllVendors() {
        Assert.assertNotNull("Data on demand for 'Vendor' failed to initialize correctly", dod.getRandomVendor());
        long count = Vendor.countVendors();
        Assert.assertTrue("Too expensive to perform a find all test for 'Vendor', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Vendor> result = Vendor.findAllVendors();
        Assert.assertNotNull("Find all method for 'Vendor' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Vendor' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void VendorIntegrationTest.testFindVendorEntries() {
        Assert.assertNotNull("Data on demand for 'Vendor' failed to initialize correctly", dod.getRandomVendor());
        long count = Vendor.countVendors();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Vendor> result = Vendor.findVendorEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Vendor' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Vendor' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void VendorIntegrationTest.testFlush() {
        Vendor obj = dod.getRandomVendor();
        Assert.assertNotNull("Data on demand for 'Vendor' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Vendor' failed to provide an identifier", id);
        obj = Vendor.findVendor(id);
        Assert.assertNotNull("Find method for 'Vendor' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyVendor(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Vendor' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void VendorIntegrationTest.testMergeUpdate() {
        Vendor obj = dod.getRandomVendor();
        Assert.assertNotNull("Data on demand for 'Vendor' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Vendor' failed to provide an identifier", id);
        obj = Vendor.findVendor(id);
        boolean modified =  dod.modifyVendor(obj);
        Integer currentVersion = obj.getVersion();
        Vendor merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Vendor' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void VendorIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Vendor' failed to initialize correctly", dod.getRandomVendor());
        Vendor obj = dod.getNewTransientVendor(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Vendor' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Vendor' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Vendor' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void VendorIntegrationTest.testRemove() {
        Vendor obj = dod.getRandomVendor();
        Assert.assertNotNull("Data on demand for 'Vendor' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Vendor' failed to provide an identifier", id);
        obj = Vendor.findVendor(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Vendor' with identifier '" + id + "'", Vendor.findVendor(id));
    }
    
}
